### ISSUE TITLE
Schema change on Agents table

### ISSUE THREAD

**Issue by jakedave** [singer-io/tap-zendesk-chat#26]
While running an extraction, we received:
```json
Error persisting data to Stitch: 400: {'error': 'Record 0 for table agents did not conform to schema:\n#: #: no subschema matched out of the total 2 subschemas\n#: expected: null, found: JSONObject\n#: extraneous key [enabled_departments] is not permitted\n'}
```
Similar to issues #15 and #22 it appears that the following line needs to be added to [agents.json](https://github.com/singer-io/tap-zendesk-chat/blob/master/tap_zendesk_chat/schemas/agents.json):
```json
  "properties": {
   ...
    "enabled_departments": {
      "type": [
        "null",
        "array"
      ]
    },
    ...
}
```
[Source](https://developer.zendesk.com/rest_api/docs/chat/agents).

If this is correct. I am happy to open a PR against the repo for this issue.

**Comment by brake21** [comment]
@jakedave Thanks for the quick look at the issue. What would be the timeline for this thing to work ?

**Comment by jakedave** [comment]
@brake21 I opened a PR #27.  I am waiting for the repo maintainers to merge this
