### ISSUE TITLE
Zendesk_Chat Errors during transform - stitch integration to redshift

### ISSUE THREAD

**Issue by amyfeng-klaviyo** [singer-io/tap-zendesk-chat#40]
logs as follow: 
[raw_extraction_logs.txt](https://github.com/singer-io/tap-zendesk-chat/files/8287177/raw_extraction_logs.txt)

**Comment by Vi6hal** [comment]
Hi @amyfeng-klaviyo 
this issue was reported earlier (#38 #39)
this issue is fixed in the following P.R https://github.com/singer-io/tap-zendesk-chat/pull/41
and released in version 0.3.2
closing this ticket
